### ISSUE TITLE
--with-qat_engine_id stops working in v0.6.2

### ISSUE THREAD

**Issue by mythi** [intel/QAT_Engine#176]
I have:

```
   cd /QAT_Engine && \
    ./autogen.sh && \
    ./configure \
    --disable-ipsec_offload \
    --disable-multibuff_offload \
    --with-qat_engine_id=qat-hw && \
```

I get:
`/usr/lib64/engines-1.1/qatengine.so`

This is regression from `v0.6.1`.

**Comment by Yogaraj-Alamenda** [comment]
@mythi , Previously it used to generate engine library in the name given in --with-qat_engine_id, Now its not created instead the library name will always be qatengine.so. This is to reduce overhead in Makefile and configure.   If library name needs to be changed, then user has to  manually change the library in the engines dir to the name given in -with-qat_engine_id . This is called out in README .

--with-engine_id="<engine_id>"
   This option needs to be specified if you want to use an engine id other than
   the default which is now "qatengine" (previously it was "qat"). This option
   can be used to set engine id as "qat" for application that still uses older
   engine id within the application. Additionally, qatengine library name in the
   OpenSSL engine install dir has to be renamed with the engine_id provided here
   (disabled by default).

**Comment by mythi** [comment]
@Yogaraj-Alamenda OK, thanks. There was no commit message explaining that user action is required.

I'm not sure whether users understand what is "engine id" if it's not the library name itself...  This also creates additional burden when building multiple flavors of the engine. Now users always have to rename the build output to something else after `make install` before starting another build.

IMO, the old behavior is much better.

**Comment by Yogaraj-Alamenda** [comment]
Yes, understand that the  old behavior was better  and sorry missed to update in commit log, the recent refactoring of the build installs library directly into engines_dir instead of standard lib dir and copy to engines dir. Having engine library name configured from user input was not possible with the new approach as we need to know the library name from configure.ac init. Hence we left that to the user to manually change library name if needed.   We are happy to accept patch if you think there is solution possible without affecting the existing build approach.

**Comment by mythi** [comment]
@Yogaraj-Alamenda no problem, I'm now renaming the engine manually. 

Closing for now but I'll keep thinking if the renaming can be done automatically.
