### ISSUE TITLE
Unable to persist VF with SRIOV 

### ISSUE THREAD

**Issue by ankitsharma5652** [intel/QAT_Engine#196]
I am using Intel QAT 8950 with SRIOV enable. I am using QAT driver 4.15, QAT Engine v0.6.10 and OpenSSL 1.1.1g on Ubuntu 20.04LTS.

I am trying to create VF with Intel QAT, to use them inside VM using KVM. But i am facing two issue:
1) Determine exact step to configure QAT for VF.  As we are not able to use PF/VF on the host machine after enable Intel Iommu.
2)  How to persist VF on the host machine to avoid losing QAT VF.

In order to use QAT Engine v0.6.10, i have to compile ipp-crypto.

For host machine, i have compile driver using
./configure --enable-icp-sriov=HOST

For virtual machine
./configure

For Openssl and QAT Engine, all steps are same as per document

**Comment by Yogaraj-Alamenda** [comment]
@ankitsharma5652 If you are going to use QAT_HW only then ipp-crypto build step is not needed. Please let me know what is the error you are seeing. Also Please follow the [installation instructions](https://01.org/sites/default/files/downloads//330689intelqatvirtualizationappnoterev0110.pdf) and use the build/configure commands mentioned in  qat_hw target 

Please refer the below [this document](https://01.org/sites/default/files/downloads//330689intelqatvirtualizationappnoterev0110.pdf) for installing QAT driver and configuration for virtualization and see it it helps.

**Comment by ankitsharma5652** [comment]
@Yogaraj-Alamenda  Thanks for the document. I go through the document and  able to setup QAT_HW using virtualization. For setup, i used QAT Engine v0.6.8 with latest QAT Driver.  I am create VF on the HOST machine using SRIOV and VF engine are UP.  In order to start VF, i have to run command in below order i.e.

```
service qat_service stop
service qat_service start

service qat_service_vfs stop
service qat_service_vfs start
```

But i am facing issue to persist created VF after reboot of the machine. After machine reboot, my VF engine are gone and i have to manual make them up. Is there any step i missed or should i refer to create custom service to make VF UP on the reboot, if  so, then when we should start qat service manually?

**Comment by jdschuet** [comment]
@ankitsharma5652 - This is expected behavior from the driver perspective.  
It is possible to create custom service to the start the VFs.  
# cat /etc/systemd/system/
[Unit]
Description=Start the QAT driver and associated vfs.
# Wait until qat.service has started prior to running this script
After=qat.service     

[Service]
Type=simple
ExecStart=/bin/bash /usr/local/bin/start_qat_vfs.sh

[Install]
WantedBy=multi-user.target

# cat  /usr/local/bin/start_qat_vfs.sh
service qat_service stop
service qat_service start
service qat_service_vfs start
service qat_service_vfs status


Please let me know if there are any additional questions.

**Comment by ankitsharma5652** [comment]
@jdschuet Thank you for solution. I able to persist VF after reboot using systemd service
