### ISSUE TITLE
No URL to download HW driver for SPR

### ISSUE THREAD

**Issue by kkurzacz-intel** [intel/QAT_Engine#278]
Hello, regarding hardware requirements for Xeon 4th gen, there is a section:

Intel® Xeon® Scalable Processor family with Intel® QAT Gen4/Gen4m	Intel® QAT Software for Linux* - [Getting Started Guide Hardware v2.0](https://cdrdv2.intel.com/v1/dl/getContent/632506)

However, this PDF mentions tarball with drivers which is not included to the manual. You can see that in section "3.2 Unpacking the Software" of the PDF. No information where get the driver from. Can you please provide it?

**Comment by Yogaraj-Alamenda** [comment]
@kkurzacz-intel I will ask the concerned team to add the URL to document.  Since this document is also from the same URL page may be they didn't add the URL inside this document. 

Please find the URL of v2.0 driver [here](https://www.intel.com/content/www/us/en/download/765501/intel-quickassist-technology-driver-for-linux-hw-version-2-0.html?)

**Comment by mythi** [comment]
> However, this PDF mentions tarball with drivers which is not included to the manual.

it's worth pointing out that Xeon 4th gen works fine with upstreamed drivers too so users don't need to worry about out-of-tree driver tarballs. e.g., Ubuntu 22.04.3 with the HWE kernel works fine.

**Comment by kkurzacz-intel** [comment]
Hello, thank you for your help. Yeah this URL solves the issue
