### ISSUE TITLE
engine or provider, why not both?

### ISSUE THREAD

**Issue by vitalyk-radware** [intel/QAT_Engine#284]
it seems that when we configure with --enable-qat_provider,  the engine library  is not  generated.
 even if we link our program with all relevant obj files and can load QAT Engine, it does not work sometimes.
 
 why Make does produce both engine and provider?

thanks!

**Comment by Yogaraj-Alamenda** [comment]
Hi @vitalyk-radware the code in engine and provider is protected under respective conditional compile flags so you would get either engine library or provider library when corresponding build flag is specified as enabling engine and provider involves much more code refactor and duplication to get both enabled together and is not needed as engine will be deprecated.

Since library location of engine and provider are 2 different paths you can build  with provider flag enabled which will install qatprovider.so in the provider path _<openssl_install_path>/lib64/ossl-modules_ and when provider flag not enabled (engine library default) qatengine.so in the path _<openssl_install_path>/lib64/engines-3_ for the same openssl library.

**Comment by vitalyk-radware** [comment]
thanks, i understand
