### ISSUE TITLE
Question about QAT hardware performance improvement.

### ISSUE THREAD

**Issue by konishi-av** [intel/QAT_Engine#3]
Please help me on this question.
I make a nginx patch and do encrypted communication using `ECDHE-RSA-AES256-GCM-SHA384`.

A passable performance was given, but I did not expect it.

It seems to take time at `qat_ecdh_compute_key` called from `qat_ec.c` after I monitor callgraph using valgrind.
It is described to a source as follows: 

> /\* Unsupported curve: X25519.
> - Detect and call it's software implementation.
>    */

Does this not support it with the QAT hardware board?
Or do you support it in a road map? When is it?

In addition, it seems to take time in particular `EC_POINT_get_affine_coordinates_GFp` called from `qat_ecdh_compute_key`.
But `EC_POINT_get_affine_coordinates_GFp` is hardly called if I use `OpenSSL 1.1.0 pre5` software not QAT.

I attach the results that I tried.

[Results using QAT hardware](https://github.com/01org/QAT_Engine/files/390703/nginx-qat.zip)
[Results using only OpenSSL 1.1.0 pre5 software](https://github.com/01org/QAT_Engine/files/390702/nginx-pre5.zip)
[Results screenshot of executing the kcachegrind](https://cloud.githubusercontent.com/assets/17001299/17251352/56a49026-55e3-11e6-965f-da1f1e37b3fe.png)

Kind regards,

**Comment by stevelinsell** [comment]
The X25519 curve is not currently supported by the Intel Quickassist Technology Driver and its associated firmware. It is currently on their radar, although unfortunately at the moment I can't confirm support or a date.

With regard to your second question: the Intel Quickassist Technology API will only accept cpaCyEcPointMultiply parameter co-ordinates in affine format. This is unfortunate as the public key in the OpenSSL case requires a conversion of the co-ordinates (via the EC_POINT_get_affine_coordinates_GFp) before they are passed down. Converting to affine co-ordinates appears to be a relatively costly operation. In the standard Software Implementation the co-ordinates do not need to be converted to do the point multiply.
I have asked the Intel Quickassist Technology Driver Team why co-ordinates are required in affine format (API limitation or driver/firmware limitation) and I will get back to you with their response.

Kind Regards,

Steve.

**Comment by konishi-av** [comment]
Hello, Steve

Thank you for your comment.
I look forward to your feedback.

Kind Regards,

Tom.

**Comment by mulichao** [comment]
Hi, @stevelinsell ,

Any update for the second question? thanks.

Regards,
Lichao

**Comment by stevelinsell** [comment]
Hi @mulichao,

I did investigate this issue.
The reason the QuickAssist interface requires affine coordinates is because this is the expected form that an elliptical curve point (P) is expressed in: (XP, YP). Standards such as [NIST.SP.800-56Ar2](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar2.pdf) give requirements in terms of affine co-ordinates so it makes sense for the QuickAssist API's to use this format. Jacobian co-ordinates on the other hand are generally used internally purely as a performance optimization. External interfaces almost always stick to affine format as that is the format points need to be in for transfer over protocols such as TLS.
This problem is pretty specific to OpenSSL. OpenSSL uses Jacobian co-ordinates as it's internal representation within EC_POINT. Due to the way OpenSSL engines hook in means that the EC_POINT is what we have available to populate the parameters of the offload request to QuickAssist. This results in an expensive conversion from Jacobian to affine on every request.
The QuickAssist Technology Driver Team have confirmed that there is no technical limitation to accepting coordinates in Jacobian format and returning them in Jacobian format at the QuickAssist API.
The next steps will be to raise a request with them to add new API calls for elliptical curve operations that take Jacobian coordinates.
Unfortunately as this problem is specific to OpenSSL and something of a workaround I'm not sure whether it will be considered as a priority, as such I cannot give an outlook of when this functionality will be available.

Kind Regards,

Steve.
