### ISSUE TITLE
QAT heartbeat fail

### ISSUE THREAD

**Issue by duadbsgh** [intel/QAT_Engine#42]
Good morning.

Thank you for helping me develop the QAT project today.

Earlier I asked you about the question of Openssl 1.1.0 f + QAT ASYNC,
I have another question today.

Symptoms :  /proc/icp_dh895xcc_dev0/heartbeat fail
driver = Intel qatmux.l.2.6.0-60
openssl= openssl-1.0.1m-async patch version

**Confirmation result** 

  lspci | grep QAT
  03:00.0 Co-processor: Intel Corporation DH895XCC Series QAT (rev ff) 

  cat /proc/icp_dh895xcc_dev0/heartbeat
  ERROR: Qat is not responding. Please restart the device

 syslog
 kernel: [2260339.545137] icp_qa_al err: put_msg_sync: Failed to receive an admin response from AE.
 kernel: [2260339.545179] [error] QatCtrl_SendSyncMsg() - : AE failed to respond to admin cmd 7, status:-1
 kernel: [2260339.545182] [error] QatCtrl_SendHeartbeat_dh895x() - : Send Heartbeat message SYNC failed.
 kernel: [2260339.545184] [error] QatCtrl_Heartbeat() - : Heartbeat failed.
kernel: [2260339.545185] [error] QatCtrl_Heartbeat() - : Device needs to be restarted.

**special note**
1.
 It didn't happen from scratch,
 Every month, every 2 days ... Irregular occurrence...

2.
No SSL data sent to QAT

3. 
heartbeat cycle time : 1~2 seconds

If you don't settle for ./adr_ctl reset,
Is that a problem with hardware?

Thank you !

**Comment by stevelinsell** [comment]
Hi @duadbsgh,

A heartbeat failure is usually caused by a hang in the QAT Acceleration Device firmware/hardware. As you have found a reset usually resolves the issue. This hang could be caused by a hardware issue, it could be caused by a bug in the device firmware, or it could be caused by the QAT Driver passing invalid memory addresses down to the device. It is pretty much impossible for me to tell which of those is causing the issue in your case. My suggestions would be if possible swap in a second card and see if that behaves the same. If it does it is probably not the hardware itself that is causing the issue.

Are you aware that you can build the QAT Driver to automatically reset when a heartbeat failure is detected?
The details are in Section 4.9 of the [Intel® Communications Chipset 8925 to 8955 Series Software - Programmer's Guide](https://01.org/sites/default/files/page/330751-006_clc_pg.pdf). You need to build the QAT Driver with the ICP_AUTO_DEVICE_RESET_ON_HB compile flag. This may help you recover when this situation occurs.

Problems of this nature with the QAT Acceleration Device itself are probably outside of the realms of what we can support in this forum which is focused on helping people integrate their OpenSSL based applications with the QuickAssist Hardware. I would suggest that if you manage to get a repeatable scenario that always causes a hang then you report it through the normal Intel support channels. 

Kind Regards,

Steve.

**Comment by duadbsgh** [comment]
Hi @stevelinsell 

Thank you.

With the ICP_AUTO_DEVICE_RESET_ON_HB flag
There was no effect, so I concluded that it is a hardware aware problem.

**Comment by stevelinsell** [comment]
Hi @duadbsgh,

That is strange that using the flag does not seem to have an effect.
Can you confirm how you are using the heartbeat feature. Are you doing a:
`cat /proc/icp_dh895xcc_dev0/heartbeat`
only after your traffic stops working or are doing it on a regular cadence, say every 30 seconds via a script/daemon?
When you say the flag has no effect, do you get a message in the system log saying that the device is being restarted? If the flag is working you should get an additional message after the:
`kernel: [2260339.545185] [error] QatCtrl_Heartbeat() - : Device needs to be restarted.`
Something along the lines of:
`ERROR: QAT is not responding and it will be restarted.`
Do you see anything like this?

Kind Regards,

Steve.

**Comment by stevelinsell** [comment]
Closed due to inactivity.
