### ISSUE TITLE
QAT Performance with OpenSSL speed

### ISSUE THREAD

**Issue by DucTM31** [intel/QAT_Engine#46]
Hi,
I'm trying to use the QAT Engine on my server.
Following your installation instruction, I've successfully built and installed the engine with OpenSSL 1.1.0f.
But when I tried to run the speed command, the result is quite low in comparison with what is reported on the whitepaper.
Here is the result I got:
With RSA2048
[root@atca2b5 bin]# taskset -c 5 ./openssl speed -engine qat -elapsed -async_jobs 36 rsa2048
engine "qat" set.
You have chosen to measure elapsed time instead of user CPU time.
Doing 2048 bit private rsa's for 10s: 56206 2048 bit private RSA's in 10.01s
Doing 2048 bit public rsa's for 10s: 988618 2048 bit public RSA's in 10.00s
OpenSSL 1.1.0f  25 May 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/root/OpenSSL_1.1.0f/\"" -DENGINESDIR="\"/root/OpenSSL_1.1.0f/lib/engines-1.1\""  -Wa,--noexecstack
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000178s 0.000010s   5615.0  98861.8

ECDSA-P256
                              sign    verify    sign/s verify/s
 256 bit ecdsa (nistp256)   0.0001s   0.0002s   8123.2   4370.9

ECDH-P256
                              op      op/s
 256 bit ecdh (nistp256)   0.0001s   8617.1

My CPU: Intel(R) Xeon(R) CPU E5-2658 v2 @ 2.40GHz
QAT 8900 series
Config file is taken from multi_process_optimized directory.

The device used in the white paper is 8950 series, that might be the reason. But I do not expect the performance is such great difference. So I wonder if I did something wrong at the config stage.
Anyone have any idea about this?
Thank you in advance!

**Comment by stevelinsell** [comment]
Hi @DucTM31,

The performance you are seeing is definitely because you are using a 8900 series accelerator.
If you look at the product briefs contained here:
[Intel® Communications Chipset 8900 to 8920 Series](https://www.intel.com/content/www/us/en/ethernet-products/gigabit-server-adapters/quickassist-adapter-8920-brief.html)
[Intel® Communications Chipset 8925 to 8955 Series](https://www.intel.com/content/www/us/en/ethernet-products/gigabit-server-adapters/quickassist-adapter-8950-brief.html)
You will see there is a huge difference in performance between the devices.
For instance to take RSA 2K as an example:
The 8900 series devices are rated to perform 5.5K RSA 2K sign operations per second.
The 8950 series devices are rated to perform 35K RSA 2K sign operations per second, over 6 times the performance.

The figures you are achieving for RSA 2K sign on an 8900 series device are in line with the product brief.

Kind Regards,

Steve.

**Comment by DucTM31** [comment]
Hi Steve,

So that really is the reason.
Anyway, for RSA, the performance is still great (9-10 times faster than openssl software).
But for anything related to elliptic curve, it's just roughly the same as the software.

**Comment by stevelinsell** [comment]
Hi @DucTM31, 

Sorry I forgot to answer this.
The elliptical curve numbers you measured are consistent with those we see for the 8900 series device.
Subsequent products provide increased performance for elliptical curve operations.

I will close this issue now as it has been inactive for a while.
