### ISSUE TITLE
qat_dh_generate_key() Failed to allocated memory

### ISSUE THREAD

**Issue by kenlosolid** [intel/QAT_Engine#51]
Hi,
I am writing an HTTPS client/server application to test all ciphers from SSLv3 to TLSv1.2, but when I enabled all ciphers ( SSL_CTX_set_cipher_list(ssl_ctx, "ALL:eNULL");), It crashed in approxmately 10,000,000 connections done everytime, but the application works fine with software encryption/decryption, I turned debug on for  QAT engine and OpenSSL, found the error message following:
----------------
ioctl_alloc_slab:876 ioctl call for mem allocation failed, ret = -1
[WARNING][qat_dh.c:299:qat_dh_generate_key()] Failed to allocate memory for pPV->pData
SSL error in qat_dh.c#300.
SSL error in ssl/statem/statem_srvr.c#1696.
SSL error in ssl/ssl_lib.c#1636. 
----------------
My hardware/software info:
CPU: Intel Xeon E5-1650
RAM: 16G
Accelerator: Intel QAT 620
OS: Ubuntu 14.04 TLS (kernel 3.16.x)
driver: QAT1.7.Upstream.L.1.0.3_42.tar.gz (with USDM)
engine: QAT_Engine-0.5.29.tar.gz
OpenSSL 1.1.0f

**Comment by stevelinsell** [comment]
Hi @kenlosolid,

So basically you are running out of pinned contiguous memory causing the memory allocation to fail.
Lets go through the possible causes of the failed allocation:

1) Memory leak in the QAT Engine. We do run stress tests to look for memory leaks, but not on every combination of ciphers so we shouldn't dismiss the possibility.
2) Memory leak in the application. Can you check that all your connections are getting properly cleaned up, i.e. SSL_shutdown() and SSL_free() are called on every connection, even on a failed handshake.
3) Memory fragmentation, The USDM memory driver allocates 2MB slabs by default, a system with lots going on may fragment memory to such an extent that it cannot get 2MB of contiguous memory to form the slab.
4) You are running so many parallel connections that 16GB is just not enough memory to support your load. (I would say this is unlikely as you would see the issue earlier rather than after around 10,000,000 connections).

My suggestion would be to have a look at /proc/buddyinfo when the issue occurs. This should tell you what size chunks of memory are available at that time. If there are few (or zero) larger chunks available then fragmentation is probably your issue. It is possible to reconfigure the USDM memory driver to use smaller slabs (You can go as small as 128KB for the QAT Engine) but I'd need to check whether reconfiguring with smaller slabs would have an impact on the Upstream QAT Driver which also uses USDM.

Another suggestion would be to monitor memory usage over time and see if it is increasing, if it is then it could be a memory leak, although the system is very good at caching so it's sometimes hard to know whether you are looking at a real leak. If it looks like there is a leak, then there are some debug options for the USDM which will help you look at the memory allocations remaining that aren't getting freed. I'm not familiar with them offhand, but I can find out about them if you come back and tell me your application code is cleaning up properly but it looks like it is leaking memory in the QAT Engine.

Let me know how you get on and whether you need me to find out the extra info.

Steve.

**Comment by kenlosolid** [comment]
Hi @stevelinsell,
Found the root cause, it was memory leak from my application, thanks for your help.
