### ISSUE TITLE
Error: failed to start device 0

### ISSUE THREAD

**Issue by imii1992** [intel/QAT_Engine#62]
\# openssl version
OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.0f  25 May 2017)

I installed QAT using `qatmux.l.2.6.0-60.tar.gz.`

`dh895xcc_qa_dev0.conf`  from QAT_Engine/qat/config/dh895xcc/multi_process_optimized/
```
...
[KERNEL]
NumberCyInstances = 0
NumberDcInstances = 0

[SHIM]
NumberCyInstances = 1 
NumberDcInstances = 0
NumProcesses = 32 
LimitDevAccess = 1

# Crypto - User space
Cy0Name = "UserCY0"
Cy0CoreAffinity = 0
Cy0IsPolled = 1
```

#cd /etc/init.d/
\# service qat_service start
Processing file: /etc/dh895xcc_qa_dev0.conf
Parity err reporting is disabled.
Error: failed to start device 0
There is 1 acceleration device(s) in the system:
 icp_dev0 - type=dh895xcc, inst_id=0, node_id=1,  bdf=83:00:0, #accel=6, #engines=12, state=down

```
icp_qa_al err: adf_subsystemInit: Invalid SRIOV_Enabled value, driver is built with SRIOV.
icp_qa_al err: adf_do_init: adf_subsystemInit error, stopping and shutting down
icp_qa_al err: adf_init_all: failed to initialize accelerator
icp_qa_al err: adf_init_devices: failed init accel 0
icp_qa_al err: adf_ctl_ioctl_dev_start: failed call to adf_init_devices
```

However, deleting `Cy0IsPolled` succeeds ...

please help me.

**Comment by stevelinsell** [comment]
Hi @imii1992,

I think the first thing to do is to check you can get the QAT Driver working on your machine using the default .conf file supplied with the QAT Driver package rather than the QAT Engine supplied one. In other words just try using the QAT Driver with the sample applications that come supplied in the QAT Driver package.
Can you work though the [Intel® Communications Chipset 89xx Series Software for Linux* - Getting Started Guide.](https://01.org/sites/default/files/page/330750-005_qat_gsg.pdf).
Pay particular attention to section 2.4 and setting intel_iommu=on or intel_iommu=off in your grub configuration file depending on your use of virtualization.
You should then also ensure the setting in the QAT Driver .conf file for:
`SRIOV_Enabled = X`
is set to 1 or 0 depending on your usage.
This setting is documented as follows:

> Enables or disables Single Root Complex I/O Virtualization. If enabled (set to 1), SRIOV and VT-d
> must be enabled in the BIOS. If disabled (set to 0), then SRIOV and VT-d must be disabled in the BIOS.

Note: if you adjust how your system is running you should rebuild the QAT Driver.

If adjusting these settings solves your problem then you should be able to move on to using the QAT Engine specific QAT Driver .conf files ensuring that if you needed to change the SRIOV_Enabled setting that you also change this in those .conf files.

Hope this info helps,

Steve.

**Comment by imii1992** [comment]
Hi @stevelinsell ,

As you said, I tried to run the sample application using the defult .conf file. The .conf file and the results are shown below.

```
[GENERAL]
ServicesEnabled = cy;dc

ConfigVersion = 2

cyHmacAuthMode = 1

WirelessEnabled = 0

Firmware_MofPath = dh895xcc/mof_firmware.bin
Firmware_MmpPath = dh895xcc/mmp_firmware.bin

statsGeneral = 1
statsDc = 1
statsDh = 1
statsDrbg = 1
statsDsa = 1
statsEcc = 1
statsKeyGen = 1
statsLn = 1
statsPrime = 1
statsRsa = 1
statsSym = 1

ProcDebug = 1

SRIOV_Enabled = 1

[KERNEL]
NumberCyInstances = 0
NumberDcInstances = 0

[SSL]
NumberCyInstances = 0
NumberDcInstances = 0
```

and running QAT sample code

```
# cd /QAT/QAT1.6/build/
#export LD_LIBRARY_PATH=/QAT/QAT1.6/build
#insmod ./qaeMemDrv.ko
#./cpa_sample_code

qaeMemInit started
icp_sal_userStartMultiProcess("SSL") started
There are no crypto instances
There are no crypto instances available
setupSymmetricTest():1307 Failed to start Crypto services
main():917 Error calling setupCipherTest
```

For reference, `intel_iommu=on` in my grub file. 
Virtualization and VT-d are enabled. 
`SRIOV_Enabled = 1` in the QAT Driver .conf file .
Changing the value of NumberCyInstances in [ SSL ] will produce the same result.

**Comment by stevelinsell** [comment]
Hi @imii1992,

I'm not an expert in Virtualization unfortunately, and getting the QuickAssist Driver up and running in a virtualized environment is rather out of my remit, I deal mostly with Application level integration at the QuickAssist API.
That said, have you worked through the following document:
[Using Intel® Virtualization Technology (Intel® VT) with Intel® QuickAssist Technology Application Note
](https://01.org/sites/default/files/downloads/intelr-quickassist-technology/330689qatvirtualizationappnoter006usreview.pdf)
From the document it appears that it is correct behaviour to have 1 x PF and 32 x VF's available as you are seeing.
I assume you are trying to setup a host and one of more guests that can use the acceleration.
Can you confirm the OS and kernel versions for the Host and Guests?
One other thing to note is that whilst you should set the `NumCyInstances = 0` and `NumDcInstance = 0` in the `[KERNEL]` section only, the corresponding settings in the `[SSL]` section should have instances set as those are used for User Space which is what we are interested in.

Kind Regards,

Steve.

**Comment by imii1992** [comment]
Thank you! @stevelinsell ,

It's work!
The virtualization and VT-d options are disabled and set to intel_immu = off, which works well.

Thank you for your kindness.

imii1992.
