### ISSUE TITLE
could not insert 'icp_qa_al'

### ISSUE THREAD

**Issue by imii1992** [intel/QAT_Engine#67]
Hi, I am currently installing QAT.

My QAT  is Intel QuickAssist Adapter 9850

qatmux.l.2.6.0-60.tar.gz is used for QAT installation.

```
cat /proc/version
Linux version 3.10.0-693.11.6.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Jan 4 01:06:37 UTC 2018
```

I let Installer.sh run. And i installed it without any the option.

The following error occurred during the installation process.
```
Copying Install Scripts
Build Done
Install Without Mux
Copy QAT firmware to /lib/firmware/dh895xcc
normal/SR_IOV host install
Copying mof_firmware.bin to /lib/firmware/dh895xcc
Copying mmp_firmware.bin to /lib/firmware/dh895xcc
Copying kernel obj to /lib/modules/3.10.0-693.11.6.el7.x86_64/kernel/drivers
Creating module.dep file for QAT released kernel object
This will take a few moments
Copying dh895xcc_qa_dev0.conf.v2 to /etc/dh895xcc_qa_dev0.conf
Creating startup and kill scripts
Copying Dynamic libraries to /lib64
Copying Static libraries to /lib64
Starting QAT service
modprobe: ERROR: could not insert 'icp_qa_al': Operation not permitted
There is 0 acceleration device(s) in the system:
There is 0 acceleration device(s) in the system:

        *** No issue detected in InstallerLog.txt file ***




        ***Acceleration install Complete***>

```
Do you know why this error occurs?
It could not insert 'icp_qa_al'...

Please help me...

**Comment by Yogaraj-Alamenda** [comment]
Hi @imii1992  few suggestions to try 

Are you sure you are installing the driver with root privileges ? could you please send us dmesg output during the error.
Also is there any other driver version previously installed? if so could you please uninstall it using option 4 and then try installing with option 3 from installer.sh

**Comment by imii1992** [comment]
Thank you @Yogaraj-Alamenda 

I installing the driver with root privileges.
And there is no any other driver version previously installed.
I have reinstalled several times, but it does not work.

Here is the InstallLog.txt

[InstallerLog.txt](https://github.com/intel/QAT_Engine/files/2080013/InstallerLog.txt)

**Comment by Yogaraj-Alamenda** [comment]
Hi  @imii1992 
From installer logs it looks like previous installation was not removed properly . 
I am guessing it from the below logs from InstallerLog.txt
 Copying mof_firmware.bin to /lib/firmware/dh895xcc
 _dh895xcc firmware exists, delete it first_
 Copying mmp_firmware.bin to /lib/firmware/dh895xcc
 _dh895xcc firmware exists, delete it first_ 
The directory /lib/firmware/dh895xcc will not contain any contents if its uninstalled correctly. 
Also issue dmesg command in commandline and share us the output as it might show kernel error logs if any.

**Comment by imii1992** [comment]
Hi @Yogaraj-Alamenda 

When i uninstall, mof_firmware.bin and mmp_firmware.bin are deleted.
So it looks uninstalled correctly...

```
#dmesg -c
#installer.sh
choose 4
choose 2
choose 3
[root@localhost QAT]# dmesg
[40298.529164] [error] osalIOMMUInit(): iommu is enabled,            but driver is not built with SRIOV 
[40298.529256] Error initialising osal

```
Is it related to the document below?
[https://01.org/sites/default/files/page/330689-003_virt_app_note.pdf](https://01.org/sites/default/files/page/330689-003_virt_app_note.pdf)

**Comment by Yogaraj-Alamenda** [comment]
HI @imii1992 
Looks like intel_iommu is turned ON in your system still. If your intention is not to use SRIOV then few steps to follow to turn it off:

1. In the file /etc/default/grub append the "_intel_iommu=off_" at the end of the line starting with GRUB_CMDLINE_LINUX.

Example:  GRUB_CMDLINE_LINUX="nomodeset rd.md=0 rd.lvm=0 rd.dm=0 quiet SYSFONT=latarcyrheb-sun16 rhgb  KEYTABLE=uk rd.luks=0 LANG=en_US.UTF-8 intel_iommu=off"

2. And then run "_grub2-mkconfig -o /boot/grub2/grub.cfg_" command. Now you will be able to see "intel_iommu=off" in  the file "/boot/grub2/grub.cfg" 

3. Reboot your system so that configuration takes into effect. Uninstall and reinstall the driver again using installer.sh script

If the problem still exists, disable Intel VT-d from the BIOS which will disable virtualization which will be somewhere in processor submenu and then chipset, advanced CPU configuration or Northbridge.
