### ISSUE TITLE
QAT/Nginx performance is low under asyn mode

### ISSUE THREAD

**Issue by jianqiangchen** [intel/QAT_Engine#71]
Hi
I am evaluating the QAT performance with Nginx. 

My set up is:
1. QAT card is 8950, the host is a desktop PC running Centos 7. 
[root@jianqche QAT2]# lspci | grep DH
03:00.0 Co-processor: Intel Corporation DH895XCC Series QAT

2. Nginx patch is from https://01.org/sites/default/files/downloads/intelr-quickassist-technology/nginx-1.10.3.l.0.3.1-001.tar.gz

3. OpenSSL is https://www.openssl.org/source/openssl-1.1.0f.tar.gz

4. QAT engine is https://github.com/intel/QAT_Engine/archive/v0.5.30.tar.gz

5. QAT driver is https://01.org/sites/default/files/downloads/intelr-quickassist-technology/qat1.7.upstream.l.1.0.3-42.tar.gz

The result of "openssl speed" test is good. Below are test results. We can see the performance of QAT under async mode is much higher than CPU and QAT sync mode.
+++++++++++++++++++++++++++++++++++++++++++++++  
1. CPU - RSA 2018
                      sign           verify           sign/s  verify/s
rsa 2048 bits 0.001065s 0.001059s    938.7    944.2

2. QAT - sync - RAS 2018
                      sign           verify           sign/s  verify/s
rsa 2048 bits 0.001063s 0.001062s    940.7    941.2

3. QAT - async - RSA 2018
                      sign           verify          sign/s      verify/s
rsa 2048 bits 0.000050s 0.000031s  20020.2  32320.8
+++++++++++++++++++++++++++++++++++++++++++++++  

The problem I have is the Nginx performance test result. I am using "openssl s_time" as client to do the test of new TLS connection per second.

1. Use CPU for the cryption:
One Nginx worker, CPU 76%
11543 connections in 2.14s; 5393.93 connections/user sec, bytes read 0
11543 connections in 11 real seconds, 0 bytes read per connection

2. The QAT sync mode performance is slightly higher than CPU: 
One Nginx worker, CPU 78%
13864 connections in 2.00s; 6932.00 connections/user sec, bytes read 0
13864 connections in 11 real seconds, 0 bytes read per connection

3. The QAT async mode performance is bad: 
One Nginx worker, CPU 30%
5976 connections in 2.24s; 2667.86 connections/user sec, bytes read 0
5976 connections in 11 real seconds, 0 bytes read per connection

The questions I have are:
1. I run command "cat /sys/kernel/debug/qat_dh895xcc_03:00.0/fw_counters"
to check the QAT status and I did see the firmware request/response number increased when offloading the cryption to QAT. However I see only AE0, AE3, AE6, AE9 out of total 12 engines got the request, not all of them. Not sure how to use all of the 12 engine's resource.

2. For QAT async mode, the CPU load is low, seems the nginx worker is spending too much time waiting on epoll for the async data encryption completion. Not sure if there is way to improve it.    

Any comment/suggestion?

**Comment by stevelinsell** [comment]
Hi @jianqiangchen,

In terms of your engine usage, The dh895xcc product uses a hardware arbiter to automatically load balance incoming requests across the engines. The device will start by only utilizing a few of the engines and as the load increases the requests will be spread across more of the engines. In your case above it appears that there are not enough incoming requests to fully utilize all of the engines.

In terms of performance, my answer is assuming correct functioning of the asynchronous nginx application. In that case we need to look at the differences between running asynchronously with QuickAssist and unaccelerated. 
By using QuickAssist you are making a tradeoff between latency and throughput. By that I mean it is not necessarily much faster to offload a single request due to the request being sent over the PCIe bus to the acceleration device, then the acceleration device has to DMA memory associated with servicing the request, process the request, and then DMA the result of the operation back. The real benefit is that the accelerator can do many of these operations in parallel allowing you to get much higher throughput overall. In order to see these benefits you need to have plenty of traffic coming in that can be offloaded in parallel (i.e. plenty of incoming connections). 
As such there are many things that can affect getting enough incoming connections, these include:

1) Are the clients themselves making enough connections, in other words how many s_time instances are you running and how are they configured? I'd be looking to run many s_times in parallel and averaging the results, a single s_time will not pump enough requests in parallel.
2) On the server side are you running anything that could restrict the traffic, i.e. firewalls, connection tracking etc., perhaps check the client(s) as well?
3) On the server side do you have enough file descriptors configured per process and system wide? An extra file descriptor is needed per connection for the eventfd used for asynch notifications.
4) Is your server configured to allow access to enough ports to support all the incoming connections?
5) Is nginx itself configured to accept enough connections in the nginx.conf?
 
Out of the above I would expect the amount of s_times you are running to have most impact, the rest will just restrict your performance to an upper limit and could prevent you reaching 40K RSA 2K operations per second.

Let me know if this helps you any,

Steve.

**Comment by stevelinsell** [comment]
Hi @jianqiangchen,

If what I have posted above does not help you then I would also recommend posting the same question to:
https://github.com/intel/asynch_mode_nginx/issues
as the problem your are experiencing is specific to running with asynchronous nginx with QuickAssist, i.e. the QAT Engine is working as expected with OpenSSL speed.

Kind Regards,

Steve.

**Comment by jianqiangchen** [comment]
Hi @stevelinsell 
Thank you very much. Your explanation is clear, now I understand the trade off between the latency and throughput of QAT. By increasing the s_time instances, now I can get a much better performance(connections per second) for QAT asyn mode than CPU(double the numbers). Will try other system tuning and check the final result.

Thanks,
Jason
