### ISSUE TITLE
FIPS mode

### ISSUE THREAD

**Issue by felix94536** [intel/QAT_Engine#74]
May I ask if there is any concern for FIPS mode support for QAT? 

I noticed in qat_ecdh_generate_key(), if it's in FIPS mode, the code is different. What's the reason for this?

Thanks.

**Comment by stevelinsell** [comment]
Hi @felix94536,

Good spot. This is the only reference to FIPS you will find in the QAT Engine and it should not be there, it should have been removed for the following reasons:

1) FIPS Mode is not supported in OpenSSL 1.1.0 or the upcoming OpenSSL 1.1.1, so OPENSSL_FIPS should never be defined. OpenSSL stripped out code related to FIPS and the QAT Engine should also have been updated to remove this reference. There are blog posts stating that OpenSSL are hoping to do a FIPS validation again in the future, so support in OpenSSL may return. 
2) The FIPS Canister does not support offloading to Engines, The code you reference will attempt to call back into the FIPS compliant code to perform the operation rather than offload it but in reality I don't think the Engine will ever get used if running in FIPS Mode anyway. The FIPS Canister cannot be changed to support ENGINES either without another FIPS validation cycle and it is unlikely to be a feature that would be accepted.

I would base any usage assumption on the fact that it is not possible to use QuickAssist from OpenSSL in a way that the OpenSSL FIPS validation would be valid. This is true of any hardware acceleration device that is utilised from OpenSSL, either they will use a modified OpenSSL (which automatically breaks the FIPS validation) or they will use an ENGINE that means they cannot be accessed under FIPS mode.  

I will get a defect raised to remove this erroneous code relating to FIPS.

Kind Regards,

Steve.

**Comment by felix94536** [comment]
Thanks for the confirmation, Steve. Closing the issue.
