### ISSUE TITLE
Compile err with Openssl

### ISSUE THREAD

**Issue by mrpre** [intel/QAT_Engine#99]
Qat_Engine :v0.5.39  
Driver: upstream  
openssl: 1.1.1  
  
Error when do `make`:  
$make
`
perl /home/shangxu.cjy/code/openssl/util/mkerr.pl -conf e_qat.ec -rebuild -reindex e_qat.c qat_fork.c qat_events.c qat_callback.c qat_polling.c qat_asym_common.c qat_utils.c qat_rsa.c qat_rsa_crt.c qat_ciphers.c qat_dh.c qat_dsa.c qat_ec.c qat_prf.c  cmn_mem_drv_inf.c e_qat_err.c && make  all-am
Can't locate configdata.pm in @INC (@INC contains: . /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /me/code/openssl/util/mkerr.pl line 13.
BEGIN failed--compilation aborted at /me/code/openssl/util/mkerr.pl line 13.
make: *** [all] Error 2
`  
When I just replaced  mkerr.pl  with it self in openssl 1.1.0, It worked.

**Comment by stevelinsell** [comment]
Hi @mrpre,

Please see the last paragraph of the troubleshooting section of the README.md:
https://github.com/intel/QAT_Engine/blob/master/README.md#troubleshooting
OpenSSL changed their build scripts on OpenSSL 1.1.1 onwards and require that the PERL5LIB environment variable has been set to include the OpenSSL path in order to find the configdata.pm perl module that the mkerr.pl script uses. Once you add the OpenSSL folder to your PERL5LIB environment variable you should be able to build successfully.

Kind Regards,

Steve.

**Comment by mrpre** [comment]
Thx.
